const ADMIN = ["dental-admin", "admin"];
const CLINICAL = [...ADMIN, "doctor", "staff", "csa"];
const VENDOR_ROLE = ["vendor"];

export const MENU = [
  { section: "Overview" },
  { id: "dashboard", label: "Dashboard", icon: "📊", path: "/" },
  { section: "Organization", accountTypes: ["enterprise"] },
  { id: "enterprises", label: "Enterprises", icon: "🏛️", path: "/enterprises", roles: ADMIN, accountTypes: ["enterprise"] },
  { id: "branches", label: "Branches", icon: "🏢", path: "/branches", roles: ADMIN, accountTypes: ["enterprise"] },
  { section: "Management" },
  { id: "doctors", label: "Doctors", icon: "👨‍⚕️", path: "/doctors", roles: ADMIN },
  { id: "staff", label: "Staff", icon: "🧑‍💼", path: "/staff", roles: ADMIN },
  { id: "patients", label: "Patients", icon: "👥", path: "/patients", roles: CLINICAL },
  { id: "vendors", label: "Vendors", icon: "🚚", path: "/vendors", roles: [...ADMIN, ...VENDOR_ROLE] },
  { section: "Appointment" },
  { id: "appointments", label: "Appointments", icon: "📅", path: "/appointments", roles: CLINICAL },
  { id: "follow-ups", label: "Follow-ups", icon: "🔁", path: "/follow-ups", roles: CLINICAL },
  { id: "reminder", label: "Reminder", icon: "🔔", path: "/notifications", roles: ADMIN },
  { id: "treatments", label: "Treatments", icon: "🦷", path: "/treatments", roles: CLINICAL },
  { section: "Reports" },
  { id: "reports-treatment", label: "Treatment Reports", icon: "🦷", path: "/reports?type=treatment-report", roles: CLINICAL },
  { id: "reports-dos-donts", label: "Do's & Don'ts", icon: "📌", path: "/reports?type=dos-donts", roles: CLINICAL },
  { id: "reports-xray", label: "X-Rays", icon: "🩻", path: "/reports?type=xray", roles: CLINICAL },
  { id: "reports-prescription", label: "Prescription", icon: "💊", path: "/reports?type=prescription", roles: CLINICAL },
  { id: "reports-lab", label: "Lab Reports", icon: "🧪", path: "/reports?type=lab-report", roles: CLINICAL },
  { section: "Finance" },
  { id: "billing", label: "Billing", icon: "💳", path: "/billing", roles: CLINICAL },
  { id: "estimates", label: "Estimated", icon: "🧾", path: "/estimates", roles: CLINICAL },
  { id: "billed", label: "Billed", icon: "📄", path: "/billing?status=paid", roles: CLINICAL },
  { section: "Settings" },
  { id: "procedures", label: "Procedures", icon: "📝", path: "/procedures", roles: ADMIN },
  { id: "finance", label: "Finance", icon: "💰", path: "/finance", roles: ADMIN },
  { id: "attendance", label: "Attendance", icon: "🕒", path: "/attendance", roles: [...ADMIN, "security"] },
  { id: "inventory", label: "Inventory", icon: "📦", path: "/inventory", roles: [...ADMIN, "housekeeping"] },
  { id: "equipment", label: "Equipment", icon: "🛠️", path: "/equipment", roles: [...ADMIN, "housekeeping"] },
  { id: "call-logs", label: "Call Logs", icon: "📞", path: "/call-logs", roles: CLINICAL },
  { section: "Portal" },
  { id: "patient-portal", label: "My Records", icon: "🩺", path: "/patient-portal", roles: ["patient"] },
  { id: "vendor-portal", label: "Vendor Portal", icon: "📦", path: "/vendor-portal", roles: VENDOR_ROLE },
];
